# Generated by Django 5.2.6 on 2025-09-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_pendingregistration_consent_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='consent_timestamp',
        ),
    ]
