# Generated by Django 5.2.6 on 2025-09-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_pendingregistration_consent_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='id_number',
        ),
    ]
